# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_auto_20170815_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
