# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_auto_20170820_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
