# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_answeruservote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervoteup',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answervoteup',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnswerVoteUp',
        ),
    ]
