# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0012_answer_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='askme.Answer'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='askme.Question'),
        ),
    ]
