# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0014_answeruservote_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
