# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0015_question_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_pub',
            field=models.DateField(auto_now_add=True),
        ),
    ]
